version: '3'

services:
    frontend:
        build: 
            # apache
            #context: ./apache/
            #dockerfile: apache.Dockerfile

            # niginx
            context: ./nginx/
            dockerfile: nginx.Dockerfile

        container_name: django_webserver

        restart: always
        depends_on: 
            - backend

        volumes: 
            # nginx
            - ./django/rest/:/usr/share/nginx/

        ports: 
            - '8080:80'


    backend:
        build:
            context: ./django/
            dockerfile: django.Dockerfile

        container_name: django_restapi

        restart: always
        depends_on: 
            - db

        volumes:
            #defining other save place
            - ./django/rest/:/var/www/

        stdin_open: true
        tty: true


    db:
        build:
            context: ./mariadb/
            dockerfile: mariadb.Dockerfile

        container_name: mariadb

        restart: always

        environment: 
            MYSQL_ROOT_PASSWORD: rootadminuser
            MYSQL_DATABASE: Django
            MYSQL_USER: django
            MYSQL_PASSWORD: djangosqlrootadmin

        volumes:
            - db_data:/var/lib/mysql

volumes: 
    db_data: {}