version: '3'

services:
    frontend:
        build: 
            context: ./apache/
            dockerfile: apache.Dockerfile

        container_name: django_webserver

        restart: always
        depends_on: 
            - db

        volumes: 
            - ./django/:/var/www/html/

        ports: 
            - '8080:80'

    db:
        build:
            context: ./mariadb/
            dockerfile: mariadb.Dockerfile

        container_name: mariadb

        restart: always

        environment: 
            MYSQL_ROOT_PASSWORD: rootadminuser
            MYSQL_DATABASE: Django
            MYSQL_USER: django
            MYSQL_PASSWORD: djangosqlrootadmin

        volumes:
            - db_data:/var/lib/mysql

volumes: 
    db_data: {}